### ISSUE TITLE
Powston App appears to be triggering actions early

### ISSUE THREAD

**Issue by outdoorbloke** [powston/app#14]
Powston App seems to be triggering actions early 

![image](https://github.com/user-attachments/assets/83466112-1444-40e0-8e2b-1ee5f55ca94c)

![image](https://github.com/user-attachments/assets/df981ea0-b579-45cd-8f41-487ccce950a6)

Code is not set to import until 11am however the import got triggered at least 2 minutes early

**Comment by iconnor** [comment]
The interval time is the NEM's window so it is the end time. At 10:55, we are in the 11:00 window.
