### ISSUE TITLE
Missing action logs

### ISSUE THREAD

**Issue by iconnor** [powston/app#2]
Some actions are not being logged:

![image](https://github.com/user-attachments/assets/1a76e5a5-13c2-4a77-881f-1a281c5b30da)

Need:
* better debug around the actions
* better clarity on where prices are sourced and quality (exp vs fcst)

**Comment by iconnor** [comment]
Adding LocalVolts variables for buy/general and sell/feed_in prices:

<img width="406" alt="image" src="https://github.com/user-attachments/assets/427a7cb3-30c5-48ac-b545-a390eb29185f">

**Comment by iconnor** [comment]
There is a UI change also, that will let you dig into the params available in the script (well technically after your custom code ran) so you can expand into all the details to see if the action makes sense given the params:
<img width="625" alt="image" src="https://github.com/user-attachments/assets/ec7e05b0-6c8b-4484-9d58-ce07b40e9149">

**Comment by chaosd0gg** [comment]
Looks like its just a FireFox issue, but the Reason field needs a text wrap or something since the UI change, currently it bleeds into the values coloumn as well

![image](https://github.com/user-attachments/assets/c1531865-a6bb-4a63-b0bb-1b4a30dd4155)

**Comment by iconnor** [comment]
Deployed a fix that will log bad actions so any skipped windows are better documented for user action. This was caused by setting the action to 'chargestopped' rather than 'charge' or 'stopped' so not a crash but an invalid state that should have been reported back to the user not silently handled.
