### ISSUE TITLE
PVOutput.org Integration

### ISSUE THREAD

**Issue by rbollar** [powston/app#8]
Among the lowest of **low priorities** would be an option to feed to PVOutput.org. It's another way to display array performance data that I often use. I currently feed through Home Assistant, so I'm not missing out on anything, but if it were easier to set up, maybe there's also some marketing benefit from having a "Powston Team" reporting data.

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/8f08a223-e918-4c63-bb22-7959aac94021">
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/8ad664a3-43d3-4e5a-b24e-f607699b8502">
<img width="996" alt="image" src="https://github.com/user-attachments/assets/14de09c3-e89d-4376-867f-189d2bb6dff6">

`rest_command:
  update_pvoutput:
    url: https://pvoutput.org/service/r2/addstatus.jsp
    method: post
    content_type: "application/x-www-form-urlencoded"
    headers:
      X-Pvoutput-Apikey: 'apikey'
      X-Pvoutput-SystemId: 'systemid'
    payload: >-
      {% set total_battery_charging_energy = states('sensor.inverter_43924_battery_charge') | float(0) + states('sensor.inverter_43924_battery_charge') | float(0) %}
      {% set total_battery_discharging_energy = states('sensor.inverter_43924_battery_discharge') | float(0) + states('sensor.inverter_43923_battery_discharge') | float(0) %}
      {% set total_pv_energy = (states('sensor.inverter_43924_solar_energy') | float(0) + states('sensor.inverter_43923_solar_energy') | float(0)) * 1000 %}
      {% set average_battery_percentage = ((states('sensor.inverter_43923_battery_state_of_charge') | float(0)) + (states('sensor.inverter_43924_battery_state_of_charge') | float(0))) / 2 %}
      {% set temperature_celsius = states('sensor.7c_c6_b6_58_8f_b2_8fb2_temperature') | float(0) %}
      {% set total_voltage = (states('sensor.inverter_43923_vgrid') | float(0) + states('sensor.inverter_43924_vgrid') | float(0)) / 2 %}
      {% set house_load = states('sensor.powston_house_power') | float(0) %}
      {% set current_cost_of_energy = states('sensor.grid_cost_for_bollar_local_volts_general_tariff') | float(0) %}
      {% set current_selling_price_of_energy = states('sensor.grid_cost_for_bollar_local_volts_feed_in_tariff') | float(0) %}
      {% set pv_power = (states('sensor.inverter_43923_solar_power') | float(0) + states('sensor.inverter_43924_solar_power') | float(0)) %}
      {% set current_datetime = now().strftime("%Y-%m-%d %H:%M:%S") %}
      {% set current_date = now().strftime("%Y%m%d") %}
      {% set current_time = now().strftime("%H:%M") %}
      d={{ current_date }}&t={{ current_time }}&v1={{ total_pv_energy | round }}&v2={{ pv_power | round }}&v5={{ temperature_celsius | round(1) }}&v6={{ total_voltage | round }}&v7={{ total_battery_charging_energy | round(3) }}&v8={{ total_battery_discharging_energy | round(3) }}&v9={{ house_load | round(3) }}&v10={{ average_battery_percentage | round(1) }}&v11={{ current_selling_price_of_energy | round(2) }}&v12={{ current_cost_of_energy | round(2) }}&m1={{ current_datetime }}
`

**Comment by iconnor** [comment]
Something like this could do it, let you enter your own API key and I push it there for you:

<img width="307" alt="image" src="https://github.com/user-attachments/assets/99e09866-e822-4601-81ab-919a8ead604f">

**Comment by rbollar** [comment]
Yes, though ideally, it would aggregate all of the inverters at the facility and upload them together.

Also ideally, extended parameters of some sort would also be uploaded for those who are contributors to PVOutput. These are the ones I uploadL

<img width="521" alt="image" src="https://github.com/user-attachments/assets/80c22596-02c1-4eb6-9cf6-4aa811be2145">

**Comment by iconnor** [comment]
When I created mine, it seemed to want to report per inverter not per house.
![image](https://github.com/user-attachments/assets/914a5c79-90da-42b6-9da1-9f7961095e4f)
https://pvoutput.org/list.jsp?userid=121881
Looks like I can add all the systems with a small donation fee:
![image](https://github.com/user-attachments/assets/4ce6aa7b-ca8a-48d6-a75b-b91722935eb6)

**Comment by rbollar** [comment]
Well, it's the line directly above your clip. My preference is to list them as one facility. 

![image](https://github.com/user-attachments/assets/b1e984de-80cf-4c61-b8f4-d090b2dac3d3)

**Comment by iconnor** [comment]
I like that better, I didn't see that for some reason

**Comment by iconnor** [comment]
This is now on profile page, and your ID and API key can be set:
https://app.powston.com/profile

<img width="410" alt="image" src="https://github.com/user-attachments/assets/c9f5666c-4f01-49be-8adf-c087b03e5f27">
